### ISSUE TITLE
No html generated

### ISSUE THREAD

**Issue by Gorkiy** [sskyy/blade#11]
What am I doing wrong? I created simple design for testing. I got empty folders with 0 files for output:

![screenshot 2015-02-09 12 40 08](https://cloud.githubusercontent.com/assets/1039031/6101580/05fc5a54-b059-11e4-9c3d-626a19fadc97.png)

Doest this plugin support Appstore version of Sketch app? And actually what is the latest version supported now? Mine is Version 3.2.2 (9983)

Thanks
Peter

**Comment by adelevie** [comment]
I am getting this same problem for the same Sketch version.

**Comment by w3p706** [comment]
I made a pull request to fix a basic API change. It will output html, but i didn't test that much.

**Comment by singularityhacker** [comment]
This is not generating an html file for me. Version 3.6.1

**Comment by vandanasirakaje** [comment]
Was there any solution for the above problem because even i am facing the same problem :(

**Comment by lenichols** [comment]
I am experiencing the same issue
