### ISSUE TITLE
Didn't work in Sketch 3.3

### ISSUE THREAD

**Issue by lmcmz** [sskyy/blade#12]
I tried my project didn't work.
Even your Demo neither .

**Comment by Mateoone** [comment]
Any solution for the latest version of sketch ? ( 3.3.2 ) nothing is generated

**Comment by kirkzwy** [comment]
I meet the same problem too？ my version is 3.3

**Comment by lquessenberry** [comment]
After a few failed attempts, I can only attribute this issue to my troubles as well.

**Comment by dublx** [comment]
+1

**Comment by sdaitzman** [comment]
:+1:

**Comment by merkushin** [comment]
Doesn't work for 3.4.4 :( (demo too)
Creates only folders for css, js, images with reset.css and jquery-....min.js.

**Comment by paulholcomb** [comment]
having the same problem - it generates a folder structure but no files.

**Comment by seaify** [comment]
same for 3.5.2

**Comment by ermolova** [comment]
same problem for Version 3.6

**Comment by VinceXie** [comment]
same problem for Version 3.6.1

**Comment by jspeis** [comment]
same for 3.6.1

**Comment by Hackforid** [comment]
same for 3.8.x

**Comment by akapei** [comment]
+1

**Comment by lenichols** [comment]
Same +1
