### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by chapalamadugu** [sskyy/blade#14]
Hi - I use blade plugin almost every other minute. Here are the items I wish to see improvements.
- Special characters like &, bullet item characters, are every time geeky characters in output; it looses the formatting
- The fonts sometime do not fit in the width; I have to manually change from auto and give it some width

There are others but we can workaround them. Can you let me know if there are any workarounds?

Thanks.

**Comment by sskyy** [comment]
@chapalamadugu  Actually I have been working on this issue already. It seems Sketch's render mechanism is different from system when rendering characters, so the output always have some issues. I'll keep on working on this and I'll let you know when it is fixed.

**Comment by chapalamadugu** [comment]
Thanks.

On Mon, May 25, 2015 at 9:58 AM, Zhenyu Hou <notifications@github.com>
wrote:

> @chapalamadugu <https://github.com/chapalamadugu> Actually I have been
> working on this issue already. It seems Sketch's render mechanism is
> different from system when rendering characters, so the output always have
> some issues. I'll keep on working on this and I'll let you know when it is
> fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sskyy/blade/issues/14#issuecomment-105121814>.
>



-- 
Manohar Chapalamadugu
Founder & CEO, Agile CRM
mobile: 1.408.627.7649 | skype: pbx800

http://www.agilecrm.com
