### ISSUE TITLE
no HTML

### ISSUE THREAD

**Issue by disto** [sskyy/blade#18]
Hi,

A folder is created with reset.css. jQuery file but no project css file or html file.
Please advice.....

**Comment by pathapati-prasad** [comment]
Have similar problem, just css, images and js folders no content

**Comment by josetorres1198** [comment]
Same problem here no HTML what is wrong with this?

**Comment by egoens** [comment]
Having the same issue? Is this repo dead?

**Comment by paulholcomb** [comment]
I gave up and just used Zeplin.io to at least build a framework for the CSS
