### ISSUE TITLE
How to install the plugin in Sketch?

### ISSUE THREAD

**Issue by HTKT** [sskyy/blade#23]
Hi @sskyy 

Thanks for your good tool. 
I'm using the latest Sketch version 47.1. i wonder how can i install this plugin to the Sketch app?
After i download the source code, i run command "npm install" and "npm run render" but there is no Blade plugin in  Sketch.

Sorry, this is the 1st i use this plugin. 
Thanks

**Comment by sskyy** [comment]
I just release an alpha version Blade, and it is still under development. Please see #22 , I will communicate with everyone in that issue.
